spring.application.name=crudebiblioteca
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/biblioteca?createDatabaseIfNotExist=true&serverTimezone=UTC}
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
server.port=${PORT:8080}
